config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :books
	root 'homes#top'
	resources :users, only: [:index, :show, :edit, :update, :destroy]
	get "homes/about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true, length:{ maximum: 199}
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books
  validates :name, presence: true, length:{ minimum: 2, maximum: 20}
  validates :introduction, length:{ maximum: 49}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# before_action :authenticate_user!


  protected

  def after_sign_in_path_for(resource)
  	if current_user
  	user_path(@user.id)
  else
  end
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
  	@book = Book.new
    @books = Book.all
    @user = current_user
  end
  def new
    @books = Book.all
  end
  def create
  	@book = Book.new(book_params)
    @book.user_id = current_user.id
  	if @book.save
  	redirect_to book_path(@book.id)
    flash[:book] = 'Book was successfully created.'
  else
    @books = Book.all
    render :index
  end
  end
  def show
    @book = Book.find(params[:id])
    @aaa = Book.new
    @user = @book.user
    flash.now [:book_new]
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)
    flash[:book_edit] = 'Book was successfully updated.'
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
    flash[:book] = 'Book was successfully destroyed.'
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body, :user_id )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    flash.now[:notice] ='Signed in successfully.'
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id)
  else
    flash[:book] = "Name is too long (maximum is 20 characters)"
    render 'edit'
  end
  end
  def edit
  	@user = User.find(params[:id])
  end
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<div class="col-xs-3">
<h2>User info</h2>
<div>
    <%= attachment_image_tag @user, :profile_image, :fill, 100, 100 %>
</div>
<div class="profile-container">
	<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>Name</th><th><%= @user.name %></th>
		</tr>
		<tr>
			<th>Introduction</th><th><%= @user.introduction %></th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<tr>
	      <td><%= link_to "編集", edit_user_path(current_user) %></td>
	</tr>
	</tbody>
</table>

</div>
	<h2>New book</h2>
	 <%= form_for book, url: books_path do |f| %>
	 <% if @book.errors.any? %>
    <div class = "alert alert-warning">
        <ul>
            <% book.errors.full_messages.each do |book| %>
                <li><%= book %></li>
            <% end %>
        </ul>
    </div>
<% end %>
	<h4>title</h4>
	<%= f.text_field :title %>

	<h4>Opinion</h4>
	<%= f.text_area :body %>

	<h4><%= f.submit 'Create Book' %></h4>
	<% end %>
</div>

app/views/books/edit.html.erb
<section class="slice slice-lg sct-color-1">
	<div class="container">
	<div class="row">
		<div class="col-lg-4">
		</div>
		<div class="col-lg-8">
<table class="table table-striped">
	<div class="text-center">
<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
	<h4>Title</h4>
	<%= f.text_field :title %>
	<h4>Body</h4>
	<%= f.text_area :body %>
	<br>
	<%= f.submit 'Update Book' %>
<% end %>
	<%= link_to "Show",  book_path(@book.id) %> |
	<%= link_to "Back",  books_path %>
</div>
</table>
</div>
</div>
</div>

app/views/books/index.html.erb
<%= flash[:book] %>
<%= render 'books/index', book: @book %>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
	<tr>
			<td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40 %></td>
			<td><%= link_to book.title,book %></td>
		    <td><%= book.body %></td>
	</tr>
		<% end %>
	</tbody>
	</table>

app/views/books/new.html.erb
<%= render 'layouts/error_messages', model: f.object %>
<%= render 'books/index', books: @books %>
<h1>Books</h1>
	<% @books.each do |book| %>
	<p>Title</p>
	<span>
		<%= book.title %>
	</span>
	<p>Body</p>
	<span>
		<%= book.body %>
	</span>
	<% end %>

	<h2>New book</h2>
	<%=form_for(@book) do |f| %>
	<h4>title</h4>
	<%= f.text_field :title %>

	<h4>Body</h4>
	<%= f.text_area :body %>

	<h4><%= f.submit 'Create Book' %><h4>
	<% end %>

app/views/books/show.html.erb
<%= flash[:book_edit] %>
<%= flash[:book] %>
<%= flash.now[:book_new] %>
<%= render 'books/index', book: @aaa %>
<div class="col-xs-9">
	<h2>Book detail<h2>
<table class="table table-hover table-inverse">
	<tbody>
		<tr>
			<th colspan="3">
		</tr>
		<tr>
			<td><%= link_to(@user) do %>
			<%= attachment_image_tag @user, :profile_image, :fill, 40, 40 %><br>
			<%= @user.name %></td>
			<% end %>
	<td><%= @book.title %></td>
	<td><%= @book.body %></td>
	<td><%= link_to "Edit", edit_book_path(@book.id) %></td>
	<td><%= link_to "Destroy" , book_path(@book.id) , method: :delete, "data-confirm" => "Are you sure?"  %></td>
</tr>
</tbody>
</table>

app/views/homes/about.html.erb
<h1>Welcome to Bookers!</h1>

app/views/homes/top.html.erb
<h1>welcome to Bookers !!</h1>
	<h3>you can share and exchange your opinions, inpressions , and<br>emotions<br>
		<h3>about various books!</h3>

	  <li class="">
        <%= link_to "sign up", new_user_registration_path %>
      </li>
      <li class="">
        <%= link_to "Log in", new_user_session_path %>
    </li>

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
    <div class = "alert alert-warning">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id="slidemenu">
  <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
    <% if user_signed_in? %>
      <li class="">
        <%= link_to "Home", users_path %>
      </li>
      <li class="">
        <%= link_to 'Users', users_path %>
      </li>
      <li class="">
        <%= link_to 'Books', books_path %>
      </li>
      <li>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
    </li>
    <% else %>
    <li class="">
        <%= link_to "home", root_path %>
      </li>
      <li class="">
        <%= link_to "about", homes_about_path %>
      </li>
      <li class="">
        <%= link_to "sign up", new_user_registration_path %>
      </li>
      <li class="">
        <%= link_to "Log in", new_user_session_path %>
      </li>
    <% end %>
  </ul>
</div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/new.html.erb
<h1>Books</h1>
	<%= form_for(@list, url:"/todolists/#{@list.id}") do |f| %>
	<% @lists.each do |list| %>
	<p>Title</p>
	<span>
		<%=link_to list.title, todolist_path(list.id) %>
	</span>
	<p>Body</p>
	<span>
		<%=link_to list.body, todolist_path(list.id) %>
	</span>
	<% end %>

	<h2>New book</h2>

	<h4>title</h4>
	<%= f.text_field :title %>

	<h4>Body</h4>
	<%= f.text_area :body %>

	<h4><%= f.submit 'Create Book' %><h4>
	<% end %>

app/views/users/edit.html.erb
<%= render 'layouts/error_message', model: @user %>
<div class="container">
                  <div class="row">
                      <div class="col-xs-4 ">
                                <h2 class="form-header-title">User info</h2>
                            <div class="form-body">
                              <%= form_for(@user) do |f| %>
                                 <h4>Name</h4>
                                  <%= f.text_field :name, autofocus: true, class:"form-control", placeholder:"名前"%>
                                    <h4>Image</h4>
                                    <%= f.attachment_field :profile_image %>
                                    <h4>Introduction</h4>
                                    <%= f.text_field :introduction, autofocus: true, class:"form-control", placeholder:"自己紹介"%>
                                <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                                    <% end %>
        </div>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'books/index', book: @book %>
<div class="col-xs-9">
<h2>Users</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
	<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 40, 40 %></td>
			<td><%= user.name %></td>
			<td><%= link_to "Show" ,user_path(user) %></td>
			<% end %>
		    	</tr>
	</tbody>
	</table>

app/views/users/show.html.erb
<% flash.now[:notice] %>
<%= render 'books/index', book: @book %>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
	<tr>
			<td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40 %></td>
			<td><%= link_to book.title,book %></td>
		    <td><%= book.body %></td>
		</tr>
			<% end %>
	</tbody>
</table>
</div>

app/views/users/top.html.erb
<%= render 'books/index', books: @books %>
<div class="col-xs-9">
<h2>Books</h2>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<p><%= @book.title %></p>
			<th>Opinion</th>
			<p><%= @book.body %></p>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
	</tbody>
</table>
</div>

<h4>Title:</h4>
<p><%= @book.title %></p>
<br>
<h4>Body:</h4>
	<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %> |